services:
  gigasite-db:
    restart: always
    container_name: project-orange-db
    image: postgres:latest
    environment:
        # Use ENV variable instad of hardcoded credentials.
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: project-orange-db
    ports:
        - "5432:5432"
    volumes:
        - project_orange_data:/var/lib/postgresql/data
    
  backend:
    restart: always
    container_name: project-orange-backend
    image: ghcr.io/sm0rezdev/project-orange-backend:latest
    build:
        context: .
        dockerfile: Dockerfile
    environment:
        # Use ENV variable instad of hardcoded credentials.
        DATABASE_URL: postgres://user:password@gigasite-db:5432/project-orange-db
        DJANGO_ALLOWED_HOSTS: "localhost, 0.0.0.0"
        DJANGO_SECRET_KEY: "your-secret-key" # used for cryptographic signing, not really used, no authentication is implemented.

    ports:
        - "8000:8000"
    depends_on:
        - gigasite-db

volumes:
  project_orange_data:
      driver: local

networks:
  default:
    driver: bridge
    name: project-orange-network