services:
  db:
    restart: always
    container_name: project-orange-db
    image: postgres:latest
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: project-orange-db
    ports:
        - "5432:5432"
    volumes:
        - project_orange_data:/var/lib/postgresql/data
    
  backend:
    restart: always
    container_name: project-orange-backend
    image: project-orange-backend:latest
    build:
        context: .
        dockerfile: Dockerfile
    environment:
        DATABASE_URL: postgres://user:password@db:5432/project-orange-db
        DJANGO_ALLOWED_HOSTS: ""
        DJANGO_SECRET_KEY: "your-secret-key"

    ports:
        - "8000:8000"
    depends_on:
        - db

volumes:
  project_orange_data:
      driver: local

networks:
  default:
    driver: bridge
    name: project-orange-network