name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
      - "v*.*"
      - "v*.*.*"
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Installing dependencies
      run: |
        echo "Installing dependencies..."
        pip3 install --upgrade pip
        pip3 install -r requirements.txt

    - name: Tests
      run: |
        echo "Running tests..."
        python3 django/manage.py test

    - name: Log in to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:latest

    - name: Push the Docker image
      if: github.event_name != 'pull_request'
      run: |
        docker push ghcr.io/${{ github.repository }}:latest
        if [[ "${{ github.ref_type }}" == "tag" ]]; then
          docker tag ghcr.io/${{ github.repository }}:latest ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        fi

    - name: Remove local Docker images
      if: always()
      run: docker image prune -af
